- name: Start vms from qm start
  hosts: all
  become: true
  tasks:
    - name: qm start vm in {{ inventory_hostname }}
      shell: |
        qm start {{ item }}
      with_sequence: start=201 end=210
      when: inventory_hostname == "milano"
    - name: qm start vm in {{ inventory_hostname }}
      shell: |
        qm start {{ item }}
      with_sequence: start=211 end=220
      when: inventory_hostname == "roma"
    - name: qm start vm in {{ inventory_hostname }}
      shell: |
        qm start {{ item }}
      with_sequence: start=221 end=230
      when: inventory_hostname == "palermo"
    - name: Pause for 5 minutes to copy the image in the local disk
      ansible.builtin.pause:
        minutes: 5
    - name: Distribute the Vouchers in the rendezvous server
      copy:
        src: "{{ item }}"
        dest: "/etc/fdo/stores/rendezvous_registered/"
      with_fileglob:
        - "/etc/fdo/stores/owner_vouchers/*"
      when: inventory_hostname == "rendezvous"
    - name: Distribute the Vouchers in the owner server
      copy:
        src: "{{ item }}"
        dest: "/etc/fdo/stores/owner_vouchers/"
      with_fileglob:
        - "/etc/fdo/stores/owner_vouchers/*"
      when: inventory_hostname == "owner"
    - name: qm start vm in {{ inventory_hostname }}
      shell: |
        qm start {{ item }}
      with_sequence: start=201 end=210
      when: inventory_hostname == "milano"
    - name: qm start vm in {{ inventory_hostname }}
      shell: |
        qm start {{ item }}
      with_sequence: start=211 end=220
      when: inventory_hostname == "roma"
    - name: qm start vm in {{ inventory_hostname }}
      shell: |
        qm start {{ item }}
      with_sequence: start=221 end=230
      when: inventory_hostname == "palermo"
