- name: Automate OStree image builder
  hosts: management
  become: true
  vars_files:
    - ./vars/hosts.yml
  tasks:
    - name: Prepare blueprint templates and compose images
      block:
        - name: Enable Cockpit/Composer/Firewalld/Apache
          ansible.builtin.systemd:
            state: started
            enabled: true
            name: cockpit.socket

        - name: Create blueprint file in /tmp
          template  :
            src: "{{ item.bp_template }}"
            dest: "{{ item.bp_file }}"
          loop: "{{ toml_files }}"

        - name: Create blueprint from shell command
          shell: |
            composer-cli blueprints push "{{ item.bp_file }}"
          loop: "{{ toml_files }}"

        - name: Compose composer-cli start-ostree "{{ edge_commit_bp }}" edge-commit
          shell: |
            composer-cli compose start-ostree "{{ edge_commit_bp }}" edge-commit
          register: _create_instances

        - name: Setting host facts using complex arguments
          ansible.builtin.set_fact:
            composeID: "{{ _create_instances.stdout[8:44] }}"

        - name: Waiting for compose
          shell: |
            results=`composer-cli compose info {{ composeID }} | head -1 | awk -F " " '{print $2}'`
            while [ $results == 'RUNNING' ]
              do
                sleep 30
                results=`composer-cli compose info {{ composeID }} | head -1 | awk -F " " '{print $2}'`
                echo "WAITING"
            done
          register: _create_instances
          async: 3600  # Maximum runtime in seconds. Adjust as needed.
          poll: 0  # Fire and continue (never poll)

        - name: Waiting for compose {{ composeID }} to be completed
          async_status:
            jid: "{{  _create_instances.ansible_job_id }}"
          register: _jobs
          until: _jobs.finished
          delay: 30  # Check every 30 seconds. Adjust as you like.
          retries: 360  # Retry up to 10 times. Adjust as needed.

        - name: Check if blueprint directory exists
          ansible.builtin.stat:
            path: "/tmp/{{ edge_commit_bp }}"
          register: stat_output

        - name: Initialize rpm-ostree repo for blueprint
          when: not stat_output.stat.exists
          block:
            - name: Create blueprint directory
              ansible.builtin.file:
                path: "/tmp/{{ edge_commit_bp }}"
                mode: 0755
                state: directory

        - name: composer-cli compose image
          ansible.builtin.command: 'composer-cli compose image {{ composeID }}'
          args:
            chdir: "/tmp/{{ edge_commit_bp }}"
      when: inventory_hostname == "owner"

#        - name: Untar artifact
#          ansible.builtin.unarchive:
#            src: "/tmp/{{ edge_commit_bp }}/{{ composeID }}-commit.tar"
#            dest: /tmp/{{ edge_commit_bp }}
#            remote_src: true
#
#        - name: Get checksum from artifact
#          ansible.builtin.command:
#            cmd: "/usr/bin/ostree --repo=/tmp/{{ edge_commit_bp }}/repo rev-parse rhel/{{ base_release }}/{{ base_arch }}/edge"
#          register: checksum_output
#          changed_when: false
#
#        - name: Pull commit from artifact
#          ansible.builtin.command:
#            cmd: "/usr/bin/ostree --repo=/var/www/html/{{ edge_commit_bp }}/repo pull-local /tmp/{{ edge_commit_bp }}/repo {{ checksum_output['stdout'] }}"
#          changed_when: true
