pool_rbd: rbd
vm_prefix: device-store
pool_vms: edge_demo
bios: ovmf
cores: 1
sockets: 1
ram: 2048
boot_size: 12
vms:
  - host: milano
    vmid: 201
  - host: milano
    vmid: 202
  - host: milano
    vmid: 203
  - host: milano
    vmid: 204
  - host: milano
    vmid: 205
  - host: milano
    vmid: 206
  - host: milano
    vmid: 207
  - host: milano
    vmid: 208
  - host: milano
    vmid: 209
  - host: milano
    vmid: 210
  - host: roma
    vmid: 211
  - host: roma
    vmid: 212
  - host: roma
    vmid: 213
  - host: roma
    vmid: 214
  - host: roma
    vmid: 215
  - host: roma
    vmid: 216
  - host: roma
    vmid: 217
  - host: roma
    vmid: 218
  - host: roma
    vmid: 219
  - host: roma
    vmid: 220
  - host: palermo
    vmid: 221
  - host: palermo
    vmid: 222
  - host: palermo
    vmid: 223
  - host: palermo
    vmid: 224
  - host: palermo
    vmid: 225
  - host: palermo
    vmid: 226
  - host: palermo
    vmid: 227
  - host: palermo
    vmid: 228
  - host: palermo
    vmid: 229
  - host: palermo
    vmid: 230
mnmnt_vms:
  - host: milano
    vmid: 231
    name: manufacturing
  - host: roma
    vmid: 232
    name: rendezvous
  - host: palermo
    vmid: 233
    name: owner