username: "ctorres-redhat"
password: "PPPySiQ4TzchXwo="
api_config_path_owner: /etc/fdo/serviceinfo-api-server.yml
directory_config_api_owner: /etc/fdo-configs
rendezvous_dns: "rendezvous.carlos-lab.com"
rendezvous_ip: "192.168.1.218"
manufacturing_server: "192.168.1.216"
manufacturing_url: "{{ manufacturing_server }}:8080"
disk_device: "/dev/vda4"
ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDS/2i2dSaDtLsE3GMVWoPoG2W1Z3/20IboirqVb9XWyvmyU7ESW01rRlaBx9jXvpmhoLYeFQrNGMfCvkUoXpMArE+CkA1ZZxVkiEe+tdoRYti5F1+s+j5Z/AfaACQU3sKr1z3sg3ZpJNUCBFTfCy7LQubV++wIKsWaDUV0KdeXIPCRF9gUKtmvWgg1Z154cNt5KqO0U4RpSu/UvopROOmL9K1z98yS+ix+n5jiaqsL2cu+SmwvgyDVw7u2d2qQdG2QECH1OHM8RbKUXCJNgZBZc7w7YnWWfEseqE/5YES/ACqRSPplG85uJLrY+mwpYFp2vtb70HHxq0Kg9MUyDnrJ karlost@wlan-180-131.mxp.redhat.com"
edge_commit_bp: "edge-commit-demo-v1"
edge_commit_bp_fdo: "edge-commit-demo-fdo-v1"
toml_files:
  - bp_template: "blueprint-edge-commit.j2"
    bp_file: "/tmp/blueprint-edge-commit.toml"
  - bp_template: "blueprint-edge-commit-fdo.j2"
    bp_file: "/tmp/blueprint-edge-commit-fdo.toml"