username: "ctorres-redhat"
password: "GPPySiQ4TzchXwo="
api_config_path_owner: /etc/fdo/serviceinfo-api-server.yml
directory_config_api_owner: /etc/fdo-configs
rendezvous_dns: "rendezvous.carlos-lab.com"
rendezvous_ip: "192.168.1.218"
manufacturing_server: "192.168.1.216"
manufacturing_server_url: "http://192.168.1.216:8080"
installation_device: "/dev/vda4"
builder_blueprint_name: "edge-demo-v11"