username: "user_your_username"
password: "and_your_password"
api_config_path_owner: /etc/fdo/serviceinfo-api-server.yml
directory_config_api_owner: /etc/fdo-configs
rendezvous_dns: "rendezvous.carlos-lab.com"
rendezvous_ip: "192.168.1.218"