- name: "Configure cockpit hosts"
  hosts: management
  become: true
  tasks:
    - name: Block for cockpit server config
      block:
        - name: Reset config /etc/cockpit/machines.d/99-webui.json
          shell: |
            echo '{' > /etc/cockpit/machines.d/99-webui.json
            echo '}' >> /etc/cockpit/machines.d/99-webui.json
            for i in {201..215}
              do
              ssh -oStrictHostKeyChecking=no 192.168.1.$i echo 'Hello'
            done
        - name: Configure devices for admin access through cockpit
          blockinfile:
            path: /etc/cockpit/machines.d/99-webui.json
            insertafter: "{"
            marker: ""
            block: |2
                "192.168.1.{{ item }}" : {
                "visible" : true,
                "color" : "#dd{{ item }}c",
                "user" : "admin",
                "address" : "192.168.1.{{ item }}"
                },
            state: present
          with_sequence: start=201 end=214
        - name: Configure devices for admin access through cockpit
          blockinfile:
            path: /etc/cockpit/machines.d/99-webui.json
            insertbefore: "}"
            marker: ""
            block: |2
                "192.168.1.215" : {
                "visible" : true,
                "color" : "#dd215c",
                "user" : "admin",
                "address" : "192.168.1.215"
                }
            state: present
        - name: Remove blank spaces
          shell: |
            sed -i '/^$/d' /etc/cockpit/machines.d/99-webui.json
        - name: Restart cockpit service
          service:
            name: cockpit
            enabled: yes
            state: restarted
      when: inventory_hostname == "owner"